server:
  port: 8080
  servlet:
    context-path: /bookshop
    session:
      timeout: 30m
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookshop
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
